# Generated by Django 4.1.7 on 2023-02-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/<django.db.models.fields.related.OneToOneField>/', verbose_name='user_picture'),
        ),
    ]
