# Generated by Django 4.1.7 on 2023-02-22 18:04

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.utils.user_directory_path, verbose_name='user_picture'),
        ),
    ]
